<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\DriverTask;
use Database\Factories\DriverTaskFactory;

/**
 * 稼働依頼シーダー
 */
class DriverTaskSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $result = '';

        if (config("app.env") === "local") {
            $data = [
                [
                    'id' => 1,
                    'task_date' => "2023-03-01",
                    'request_date' => "2023-03-10",
                    'driver_id' => 1,
                    'delivery_office_id' => 2,
                    'driver_task_status_id' => 4,
                    'driver_task_plan_id' => 2,
                    'driver_task_plan_id' => 2,
                    'rough_quantity' => mt_rand(1, 100),
                    'delivery_route' => '配送コース配送コース',
                    'task_memo' => 'タスクメモ',
                    'task_delivery_company_name' => 'アマゾン',
                    'task_delivery_office_name' =>  'テスト営業所',
                    'task_email' => 'test@x.com',
                    'task_tel' => '090' . sprintf('%04d', mt_rand(1, 9999)) . sprintf('%04d', mt_rand(1, 9999)),
                    'task_post_code1' => sprintf('%03d', mt_rand(1, 999)),
                    'task_post_code2' => sprintf('%04d', mt_rand(1, 9999)),
                    'task_addr1_id' => mt_rand(1, 47),
                    'task_addr2' => "task_addr2",
                    'task_addr3' => "task_addr3",
                    'task_addr4' => "task_addr4",
                    'system_price' => 10000,
                    'freight_cost' => 5000,
                    'emergency_price' => 0,
                    'discount' => 0,
                    'tax' => 1500,
                    'tax_rate' => 10.00,
                    'refund_amount' => 0,
                    'payment_fee_rate' => 3.60,
                    'stripe_payment_method_id' => '',
                    'stripe_payment_intent_id' => '',
                    'stripe_payment_refund_id' => '',
                    'driver_task_payment_status_id' => 1,
                    'driver_task_refund_status_id' => 1,
                    'created_at' => "2023-03-01",
                    'updated_at' => "2023-03-05",
                ],
                [
                    'id' => 2,
                    'task_date' => "2123-04-01",
                    'request_date' => "2123-04-10",
                    'driver_id' => 2,
                    'delivery_office_id' => 2,
                    'driver_task_status_id' => 3,
                    'driver_task_plan_id' => 2,
                    'driver_task_plan_id' => 2,
                    'rough_quantity' => mt_rand(1, 100),
                    'delivery_route' => '配送コース配送コース',
                    'task_memo' => 'タスクメモ',
                    'task_delivery_company_name' => 'アマゾン',
                    'task_delivery_office_name' =>  'テスト営業所',
                    'task_email' => 'test@x.com',
                    'task_tel' => '090' . sprintf('%04d', mt_rand(1, 9999)) . sprintf('%04d', mt_rand(1, 9999)),
                    'task_post_code1' => sprintf('%03d', mt_rand(1, 999)),
                    'task_post_code2' => sprintf('%04d', mt_rand(1, 9999)),
                    'task_addr1_id' => mt_rand(1, 47),
                    'task_addr2' => "task_addr2",
                    'task_addr3' => "task_addr3",
                    'task_addr4' => "task_addr4",
                    'system_price' => 10000,
                    'freight_cost' => 5000,
                    'emergency_price' => 0,
                    'discount' => 0,
                    'tax' => 1500,
                    'tax_rate' => 10.00,
                    'refund_amount' => 0,
                    'payment_fee_rate' => 3.60,
                    'stripe_payment_method_id' => '',
                    'stripe_payment_intent_id' => '',
                    'stripe_payment_refund_id' => '',
                    'driver_task_payment_status_id' => 1,
                    'driver_task_refund_status_id' => 1,
                    'created_at' => "2023-04-01",
                    'updated_at' => "2023-04-05",
                ],
                [
                    'id' => 3,
                    'task_date' => "2023-05-01",
                    'request_date' => "2023-05-10",
                    'driver_id' => 2,
                    'delivery_office_id' => 1,
                    'driver_task_status_id' => 3,
                    'driver_task_plan_id' => 2,
                    'rough_quantity' => mt_rand(1, 100),
                    'delivery_route' => '配送コース配送コース',
                    'task_memo' => 'タスクメモ',
                    'task_delivery_company_name' => 'アマゾン',
                    'task_delivery_office_name' =>  'テスト営業所',
                    'task_email' => 'test@x.com',
                    'task_tel' => '090' . sprintf('%04d', mt_rand(1, 9999)) . sprintf('%04d', mt_rand(1, 9999)),
                    'task_post_code1' => sprintf('%03d', mt_rand(1, 999)),
                    'task_post_code2' => sprintf('%04d', mt_rand(1, 9999)),
                    'task_addr1_id' => mt_rand(1, 47),
                    'task_addr2' => "task_addr2",
                    'task_addr3' => "task_addr3",
                    'task_addr4' => "task_addr4",
                    'system_price' => 10000,
                    'freight_cost' => 5000,
                    'emergency_price' => 0,
                    'discount' => 0,
                    'tax' => 1500,
                    'tax_rate' => 10.00,
                    'refund_amount' => 0,
                    'payment_fee_rate' => 3.60,
                    'stripe_payment_method_id' => '',
                    'stripe_payment_intent_id' => '',
                    'stripe_payment_refund_id' => '',
                    'driver_task_payment_status_id' => 1,
                    'driver_task_refund_status_id' => 1,
                    'created_at' => "2023-05-01",
                    'updated_at' => "2023-05-05",
                ],
                [
                    'id' => 4,
                    'task_date' => "2023-07-01",
                    'request_date' => "2023-07-10",
                    'driver_id' => 2,
                    'delivery_office_id' => 1,
                    'driver_task_status_id' => 3,
                    'driver_task_plan_id' => 2,
                    'rough_quantity' => mt_rand(1, 100),
                    'delivery_route' => '配送コース配送コース',
                    'task_memo' => 'タスクメモ',
                    'task_delivery_company_name' => 'アマゾン',
                    'task_delivery_office_name' =>  'テスト営業所',
                    'task_email' => 'test@x.com',
                    'task_tel' => '090' . sprintf('%04d', mt_rand(1, 9999)) . sprintf('%04d', mt_rand(1, 9999)),
                    'task_post_code1' => sprintf('%03d', mt_rand(1, 999)),
                    'task_post_code2' => sprintf('%04d', mt_rand(1, 9999)),
                    'task_addr1_id' => mt_rand(1, 47),
                    'task_addr2' => "task_addr2",
                    'task_addr3' => "task_addr3",
                    'task_addr4' => "task_addr4",
                    'system_price' => 10000,
                    'freight_cost' => 5000,
                    'emergency_price' => 0,
                    'discount' => 0,
                    'tax' => 1500,
                    'tax_rate' => 10.00,
                    'refund_amount' => 0,
                    'payment_fee_rate' => 3.60,
                    'stripe_payment_method_id' => '',
                    'stripe_payment_intent_id' => '',
                    'stripe_payment_refund_id' => '',
                    'driver_task_payment_status_id' => 1,
                    'driver_task_refund_status_id' => 1,
                    'created_at' => "2023-07-01",
                    'updated_at' => "2023-07-05",
                ],
                [
                    'id' => 5,
                    'task_date' => "2023-07-01",
                    'request_date' => "2023-07-10",
                    'driver_id' => 3,
                    'delivery_office_id' => 2,
                    'driver_task_status_id' => 4,
                    'driver_task_plan_id' => 2,
                    'rough_quantity' => mt_rand(1, 100),
                    'delivery_route' => '配送コース配送コース',
                    'task_memo' => 'タスクメモ',
                    'task_delivery_company_name' => 'アマゾン',
                    'task_delivery_office_name' =>  'テスト営業所',
                    'task_email' => 'test@x.com',
                    'task_tel' => '090' . sprintf('%04d', mt_rand(1, 9999)) . sprintf('%04d', mt_rand(1, 9999)),
                    'task_post_code1' => sprintf('%03d', mt_rand(1, 999)),
                    'task_post_code2' => sprintf('%04d', mt_rand(1, 9999)),
                    'task_addr1_id' => mt_rand(1, 47),
                    'task_addr2' => "task_addr2",
                    'task_addr3' => "task_addr3",
                    'task_addr4' => "task_addr4",
                    'system_price' => 10000,
                    'freight_cost' => 5000,
                    'emergency_price' => 0,
                    'discount' => 0,
                    'tax' => 1500,
                    'tax_rate' => 10.00,
                    'refund_amount' => 0,
                    'payment_fee_rate' => 3.60,
                    'stripe_payment_method_id' => '',
                    'stripe_payment_intent_id' => '',
                    'stripe_payment_refund_id' => '',
                    'driver_task_payment_status_id' => 1,
                    'driver_task_refund_status_id' => 1,
                    'created_at' => "2023-07-01",
                    'updated_at' => "2023-07-05",
                ],
                [
                    'id' => 6,
                    'task_date' => "2023-04-01",
                    'request_date' => "2023-04-10",
                    'driver_id' => 2,
                    'delivery_office_id' => 2,
                    'driver_task_status_id' => 4,
                    'driver_task_plan_id' => 2,
                    'rough_quantity' => mt_rand(1, 100),
                    'delivery_route' => '配送コース配送コース',
                    'task_memo' => 'タスクメモ',
                    'task_delivery_company_name' => 'アマゾン',
                    'task_delivery_office_name' =>  'テスト営業所',
                    'task_email' => 'test@x.com',
                    'task_tel' => '090' . sprintf('%04d', mt_rand(1, 9999)) . sprintf('%04d', mt_rand(1, 9999)),
                    'task_post_code1' => sprintf('%03d', mt_rand(1, 999)),
                    'task_post_code2' => sprintf('%04d', mt_rand(1, 9999)),
                    'task_addr1_id' => mt_rand(1, 47),
                    'task_addr2' => "task_addr2",
                    'task_addr3' => "task_addr3",
                    'task_addr4' => "task_addr4",
                    'system_price' => 10000,
                    'freight_cost' => 5000,
                    'emergency_price' => 0,
                    'discount' => 0,
                    'tax' => 1500,
                    'tax_rate' => 10.00,
                    'refund_amount' => 0,
                    'payment_fee_rate' => 3.60,
                    'stripe_payment_method_id' => '',
                    'stripe_payment_intent_id' => '',
                    'stripe_payment_refund_id' => '',
                    'driver_task_payment_status_id' => 1,
                    'driver_task_refund_status_id' => 1,
                    'created_at' => "2023-08-01",
                    'updated_at' => "2023-08-05",
                ],
                [
                    'id' => 7,
                    'task_date' => "2023-08-01",
                    'request_date' => "2023-08-10",
                    'driver_id' => 1,
                    'delivery_office_id' => 2,
                    'driver_task_status_id' => 3,
                    'driver_task_plan_id' => 2,
                    'rough_quantity' => mt_rand(1, 100),
                    'delivery_route' => '配送コース配送コース',
                    'task_memo' => 'タスクメモ',
                    'task_delivery_company_name' => 'アマゾン',
                    'task_delivery_office_name' =>  'テスト営業所',
                    'task_email' => 'test@x.com',
                    'task_tel' => '090' . sprintf('%04d', mt_rand(1, 9999)) . sprintf('%04d', mt_rand(1, 9999)),
                    'task_post_code1' => sprintf('%03d', mt_rand(1, 999)),
                    'task_post_code2' => sprintf('%04d', mt_rand(1, 9999)),
                    'task_addr1_id' => mt_rand(1, 47),
                    'task_addr2' => "task_addr2",
                    'task_addr3' => "task_addr3",
                    'task_addr4' => "task_addr4",
                    'system_price' => 10000,
                    'freight_cost' => 5000,
                    'emergency_price' => 0,
                    'discount' => 0,
                    'tax' => 1500,
                    'tax_rate' => 10.00,
                    'refund_amount' => 0,
                    'payment_fee_rate' => 3.60,
                    'stripe_payment_method_id' => '',
                    'stripe_payment_intent_id' => '',
                    'stripe_payment_refund_id' => '',
                    'driver_task_payment_status_id' => 1,
                    'driver_task_refund_status_id' => 1,
                    'created_at' => "2023-08-01",
                    'updated_at' => "2023-08-05",
                ],
                [
                    'id' => 8,
                    'task_date' => "2023-08-01",
                    'request_date' => "2023-08-10",
                    'driver_id' => 2,
                    'delivery_office_id' => 2,
                    'driver_task_status_id' => 2,
                    'driver_task_plan_id' => 2,
                    'rough_quantity' => mt_rand(1, 100),
                    'delivery_route' => '配送コース配送コース',
                    'task_memo' => 'タスクメモ',
                    'task_delivery_company_name' => 'アマゾン',
                    'task_delivery_office_name' =>  'テスト営業所',
                    'task_email' => 'test@x.com',
                    'task_tel' => '090' . sprintf('%04d', mt_rand(1, 9999)) . sprintf('%04d', mt_rand(1, 9999)),
                    'task_post_code1' => sprintf('%03d', mt_rand(1, 999)),
                    'task_post_code2' => sprintf('%04d', mt_rand(1, 9999)),
                    'task_addr1_id' => mt_rand(1, 47),
                    'task_addr2' => "task_addr2",
                    'task_addr3' => "task_addr3",
                    'task_addr4' => "task_addr4",
                    'system_price' => 10000,
                    'freight_cost' => 5000,
                    'emergency_price' => 0,
                    'discount' => 0,
                    'tax' => 1500,
                    'tax_rate' => 10.00,
                    'refund_amount' => 0,
                    'payment_fee_rate' => 3.60,
                    'stripe_payment_method_id' => '',
                    'stripe_payment_intent_id' => '',
                    'stripe_payment_refund_id' => '',
                    'driver_task_payment_status_id' => 1,
                    'driver_task_refund_status_id' => 1,
                    'created_at' => "2023-08-01",
                    'updated_at' => "2023-08-05",
                ],
                [
                    'id' => 9,
                    'task_date' => "2023-08-01",
                    'request_date' => "2023-08-10",
                    'driver_id' => 2,
                    'delivery_office_id' => 2,
                    'driver_task_status_id' => 1,
                    'driver_task_plan_id' => 2,
                    'rough_quantity' => mt_rand(1, 100),
                    'delivery_route' => '配送コース配送コース',
                    'task_memo' => 'タスクメモ',
                    'task_delivery_company_name' => 'アマゾン',
                    'task_delivery_office_name' =>  'テスト営業所',
                    'task_email' => 'test@x.com',
                    'task_tel' => '090' . sprintf('%04d', mt_rand(1, 9999)) . sprintf('%04d', mt_rand(1, 9999)),
                    'task_post_code1' => sprintf('%03d', mt_rand(1, 999)),
                    'task_post_code2' => sprintf('%04d', mt_rand(1, 9999)),
                    'task_addr1_id' => mt_rand(1, 47),
                    'task_addr2' => "task_addr2",
                    'task_addr3' => "task_addr3",
                    'task_addr4' => "task_addr4",
                    'system_price' => 10000,
                    'freight_cost' => 5000,
                    'emergency_price' => 0,
                    'discount' => 0,
                    'tax' => 1500,
                    'tax_rate' => 10.00,
                    'refund_amount' => 0,
                    'payment_fee_rate' => 3.60,
                    'stripe_payment_method_id' => '',
                    'stripe_payment_intent_id' => '',
                    'stripe_payment_refund_id' => '',
                    'driver_task_payment_status_id' => 1,
                    'driver_task_refund_status_id' => 1,
                    'created_at' => "2023-08-01",
                    'updated_at' => "2023-08-05",
                ],
                [
                    'id' => 10,
                    'task_date' => "2023-03-05",
                    'request_date' => "2023-03-10",
                    'driver_id' => 2,
                    'delivery_office_id' => 2,
                    'driver_task_status_id' => 8,
                    'driver_task_plan_id' => 2,
                    'rough_quantity' => mt_rand(1, 100),
                    'delivery_route' => '配送コース配送コース',
                    'task_memo' => 'タスクメモ',
                    'task_delivery_company_name' => 'アマゾン',
                    'task_delivery_office_name' =>  'テスト営業所',
                    'task_email' => 'test@x.com',
                    'task_tel' => '090' . sprintf('%04d', mt_rand(1, 9999)) . sprintf('%04d', mt_rand(1, 9999)),
                    'task_post_code1' => sprintf('%03d', mt_rand(1, 999)),
                    'task_post_code2' => sprintf('%04d', mt_rand(1, 9999)),
                    'task_addr1_id' => mt_rand(1, 47),
                    'task_addr2' => "task_addr2",
                    'task_addr3' => "task_addr3",
                    'task_addr4' => "task_addr4",
                    'system_price' => 10000,
                    'freight_cost' => 5000,
                    'emergency_price' => 0,
                    'discount' => 0,
                    'tax' => 1500,
                    'tax_rate' => 10.00,
                    'refund_amount' => 0,
                    'payment_fee_rate' => 3.60,
                    'stripe_payment_method_id' => '',
                    'stripe_payment_intent_id' => '',
                    'stripe_payment_refund_id' => '',
                    'driver_task_payment_status_id' => 1,
                    'driver_task_refund_status_id' => 1,
                    'created_at' => "2023-08-01",
                    'updated_at' => "2023-08-05",
                ]
            ];

            $result = DB::table('driver_tasks')->insertOrIgnore($data);

            DriverTask::factory()->count(120)->create();
        }

        if (!$result) {
            echo "\033[31mSkip!!\033[0m\n";
        } else {
            echo "\033[34mDone!!\033[0m\n";
        }
    }
}
