@startsalt sample

title ログインページ
header ヘッダー
footer フッター

scale 400 width

{
    {^ "ログイン"
        ^ドロップリスト^
        プレーンテキスト
        [ボタン]
        ()  ラジオボタン
        (X) ラジオボタン
        []  チェックボックス
        [X] チェックボックス
        { プレーンテキスト: | ^リスト横並び^ }
        "input text"
        {SI
            テキストエリア
            .
            .
        }
    }
    {^ "お知らせ"
        お知らせテキスト
    }
}

@endsalt
